repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.2
    hooks:
      - id: golangci-lint
        name: Linter
        entry: golangci-lint run
        args:
          - --max-issues-per-linter=0
          - --max-same-issues=0
          - --config=.code_quality/.golangci.yaml
          - --new-from-rev=HEAD~1 # comment this arg if you want to run pre-commit run --all-files
          - --fix

  - repo: local
    hooks:
    -   id: go-unit-tests
        name: go unit tests
        entry: go test ./...
        pass_filenames: false
        types: [go]
        language: system
