version: '3.9'

services:
  postgres:
    container_name: postgres-develop-container
    image: postgres:14-alpine
    user: "${UID}:${GID}"
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=test
      - POSTGRES_DB=deviceFirmwares
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
